version: '3.7'
services:
  db:
    hostname: db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - todoapp

  api:
    hostname: api
    image: frankensteinxd/todoapi
    ports:
      - 7000:${PORT}
    environment:
      ENABLE_CORS: "false"
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      VERIFICATION_SECRET: ${VERIFICATION_SECRET}
      PASSWORD_RESET_SECRET: ${PASSWORD_RESET_SECRET}
      SENTRY_DSN: ${SENTRY_DSN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      DB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/todoapp?authSource=admin
    networks:
      - todoapp
    depends_on:
      - db
    restart: always

  front:
    hostname: frontend
    image: frankensteinxd/todofront
    ports:
      - 3000:80
    environment:
      REACT_APP_API_URL: http://localhost:7000/api/v1
    networks:
      - todoapp
    depends_on:
      - api

networks:
  todoapp: